(letrec ((server-init-actor (actor "server-init" ()
                                   (init (p x)
                                         (send p ok)
                                         (become server-actor x))))
         (server-actor (actor "server" (x)
                              (init (p x)
                                    (error "We should be already initialized!"))
                              (set (y)
                                   (become server-actor y))
                              (get (p)
                                   (send p result x)
                                   (become server-actor x))
                              (bye ()
                                   (terminate))))
         (after-init-actor (actor "after-init" (s)
                                  (ok ()
                                      (send s set 'b)
                                      (send s bye)
                                      (terminate))))
         (s (create server-init-actor))
         (after-init (create after-init-actor s)))
  (send s init after-init 'a))
