;; Random number generate sharing state among multiple thrds
(define N (+ 42 10))
(define (range from to)
  (if (= from to)
      (cons from '())
      (cons from (range (+ from 1) to))))

(define (rng seed)
  (letrec ((state (atom seed))
           (lock (new-lock)))
    (lambda ()
      (acquire lock)
      (reset! state (modulo (+ (* 5245 (read state)) 12345) 107374182))
      (let ((n (modulo (quotient (read state) 65535) 32768)))
        (release lock)
        n))))
(define gen (rng 100))
(define ts (map (lambda (x) (future (gen))) (range 1 N)))
(map (lambda (t) (deref t)) ts)
