(define wants-to-enter-0 (ref #f))
(define wants-to-enter-1 (ref #f))
(define turn (ref 0))
(define counter (ref 0))

(define (p0)
  (ref-set wants-to-enter-0 #t)
  (letrec ((wait (lambda ()
                   (if (deref wants-to-enter-1)
                       (if (not (= (deref turn) 0))
                           (letrec ((wait2 (lambda ()
                                             (if (not (= (deref turn) 0))
                                                 (wait2)
                                                 #t))))
                             (ref-set wants-to-enter-0 #f)
                             (wait2)
                             (ref-set wants-to-enter-0 #t)
                             (wait))
                           (wait))
                       #t))))
    (wait)
    ;; Critical section
    (ref-set counter (+ (deref counter) 1))
    (ref-set turn 1)
    (ref-set wants-to-enter-0 #f)))

(define (p1)
  (ref-set wants-to-enter-1 #t)
  (letrec ((wait (lambda ()
                   (if (deref wants-to-enter-0)
                       (if (not (= (deref turn) 1))
                           (letrec ((wait2 (lambda ()
                                             (if (not (= (deref turn) 1))
                                                 (wait2)
                                                 #t))))
                             (ref-set wants-to-enter-1 #f)
                             (wait2)
                             (ref-set wants-to-enter-1 #t)
                             (wait))
                           (wait))
                       #t))))
    (wait)
    ;; Critical section
    (ref-set counter (+ (deref counter) 1))
    (ref-set turn 0)
    (ref-set wants-to-enter-1 #f)))

;; Creates the two threads, which each increase counter
(define t0 (fork (p0)))
(define t1 (fork (p1)))
(join t0)
(join t1)
(= (deref counter) 2)
