(letrec ((result 1)
         (fact (lambda (i)
                 (if (= i 0)
                     result
                     (begin (set! result (* result i))
                            (fact (- i 1))))))
         (t1 (fork (fact 4)))
         (t2 (fork (fact 5))))
  (join t1)
  (join t2)
  result)
