(define (maak-rechthoek l b)
  (define (oppervlakte) (* l b))
  (define (omtrek) (* 2 (+ l b)))
  (define (dispatch m)
    (cond ((eq? m 'oppervlakte) (oppervlakte))
          ((eq? m 'omtrek) (omtrek))))
  dispatch)

(define (maak-vierkant zijde)
  (define rechthoek (maak-rechthoek zijde zijde))
  (define (schaal! n) (set! zijde (* n zijde)))
  (define (dispatch m)
    (cond ((eq? m 'oppervlakte) (rechthoek 'oppervlakte))
          ((eq? m 'omtrek) (rechthoek 'omtrek))
          ((eq? m 'schaal!) schaal!)))
  dispatch)

(define test (maak-vierkant 5))
(and (= (test 'oppervlakte) 25)
     (= (test 'omtrek) 20)
     (= (begin ((test 'schaal!) 2)
               (test 'oppervlakte))
        25))