(letrec ((counter 0)
         (inc (lambda ()
                (set! counter (+ counter 1))))
         (dec (lambda ()
                (set! counter (- counter 1))))
         (t1 (future (inc)))
         (t2 (future (dec))))
  (deref t1)
  (deref t2)
  counter)
