(letrec ((server-init-actor (a/actor "server-init" ()
                                   (init (p x)
                                         (a/send p ok)
                                         (a/become server-actor x))))
         (server-actor (a/actor "server" (x)
                              (init (p x)
                                    (error "We should be already initialized!"))
                              (set (y)
                                   (a/become server-actor y))
                              (get (p)
                                   (a/send p result x)
                                   (a/become server-actor x))
                              (bye ()
                                   (a/terminate))))
         (after-init-actor (a/actor "after-init" (s)
                                  (ok ()
                                      (a/send s set 'b)
                                      (a/send s bye)
                                      (a/terminate))))
         (s (a/create server-init-actor))
         (after-init (a/create after-init-actor s)))
  (a/send s init after-init 'a))
