;; From D'Osualdo
(letrec ((server-actor (actor "server" (state)
                              (message (x p)
                                       (send p state state)
                                       (become server-actor state))
                              (state (x) (become server-actor state))
                              (bye () (terminate))))
         (init-actor (actor "init" ()
                            (init (x)
                                  (become server-actor x))))
         (act (create init-actor)))
  (send act init 0)
  (send act message 'hi act)
  (send act message 'then act)
  (send act bye))
