;; From D'Osualdo
(letrec ((server-actor (a/actor "server" (state)
                              (message (x p)
                                       (a/send p state state)
                                       (a/become server-actor state))
                              (state (x) (a/become server-actor state))
                              (bye () (a/terminate))))
         (init-actor (a/actor "init" ()
                            (init (x)
                                  (a/become server-actor x))))
         (act (a/create init-actor)))
  (a/send act init 0)
  (a/send act message 'hi act)
  (a/send act message 'then act)
  (a/send act bye))
