(letrec ((call-loop (lambda (n f)
                      (if (= n 1)
                          (a/send f call (int-top))
                          (begin
                            (a/send f call (int-top))
                            (call-loop (- n 1) f)))))
         (factory-actor (a/actor "factory" (p)
                               (call (in)
                                     (a/send p update self in)
                                     (a/become factory-wait-actor p))))
         (factory-wait-actor (a/actor "factory-wait" (p)
                                    (done ()
                                          (a/become factory-actor p))
                                    (call (n)
                                          (a/send self call n)
                                          (a/become factory-wait-actor p))))
         (state-actor (a/actor "state" (n newstate)
                             (update (p in)
                                     (let ((m (newstate n in)))
                                       (a/send p done)
                                       (a/become state-actor m newstate)))))
         (state (a/create state-actor (int-top) (lambda (x y) (int-top))))
         (factory (a/create factory-actor state)))
  (call-loop (int-top) factory))
