(letrec ((counter 0)
         (thread (lambda (n)
                   (letrec ((old counter)
                            (new (+ old 1)))
                     (if (cas counter old new)
                         #t
                         (thread n)))))
(t1 (spawn (thread 1)))
(t2 (spawn (thread 2))))
(join t1)
(join t2))