(letrec ((counter 0)
         (inc (lambda ()
                (set! counter (+ counter 1))))
         (dec (lambda ()
                (set! counter (- counter 1))))
         (t1 (fork (inc)))
         (t2 (fork (dec))))
  (join t1)
  (join t2)
  counter)
