;; Sudoku checker
(define board
  (vector
   (vector 6 2 4 5 3 9 1 8 7)
   (vector 5 1 9 7 2 8 6 3 4)
   (vector 8 3 7 6 1 4 2 9 5)
   (vector 1 4 3 8 6 5 7 2 9)
   (vector 9 5 8 2 4 7 3 6 1)
   (vector 7 6 2 3 9 1 (<change> 4 'oops) 5 8) ; <======================================================================
   (vector 3 7 1 9 5 6 8 4 2)
   (vector 4 9 6 1 8 2 5 7 3)
   (vector 2 8 5 4 7 3 9 1 6)))

(define (walk-row i)
  (letrec ((loop (lambda (j seen)
                   (if (< j 9)
                       (if (member (vector-ref (vector-ref board i) j) seen)
                           #f
                           (loop (+ j 1) (cons (vector-ref (vector-ref board i) j) seen)))
                       #t))))
    (loop 0 '())))

(define (walk-rows)
  (let ((wr1 (fork (walk-row 0)))
        (wr2 (fork (walk-row 1)))
        (wr3 (fork (walk-row 2)))
        (wr4 (fork (walk-row 3)))
        (wr5 (fork (walk-row 4)))
        (wr6 (fork (walk-row 5)))
        (wr7 (fork (walk-row 6)))
        (wr8 (fork (walk-row 7)))
        (wr9 (fork (walk-row 8))))
    (and (join wr1) (join wr2) (join wr3)
         (join wr4) (join wr5) (join wr6)
         (join wr7) (join wr8) (join wr9))))

(define (walk-col j)
  (letrec ((loop (lambda (i seen)
                   (if (< i 9)
                       (if (member (vector-ref (vector-ref board i) j) seen)
                           #f
                           (loop (+ i 1) (cons (vector-ref (vector-ref board i) j) seen)))
                       #t))))
    (loop 0 '())))

(define (walk-cols)
  (let ((wc1 (fork (walk-col 0)))
        (wc2 (fork (walk-col 1)))
        (wc3 (fork (walk-col 2)))
        (wc4 (fork (walk-col 3)))
        (wc5 (fork (walk-col 4)))
        (wc6 (fork (walk-col 5)))
        (wc7 (fork (walk-col 6)))
        (wc8 (fork (walk-col 7)))
        (wc9 (fork (walk-col 8))))
    (and (join wc1) (join wc2) (join wc3)
         (join wc4) (join wc5) (join wc6)
         (join wc7) (join wc8) (join wc9))))

(define (check-square starti startj)
  (letrec ((loop1 (lambda (i seen)
                    (if (< i (+ starti 3))
                        (letrec ((loop2 (lambda (j seen)
                                           (if (< j (+ startj 3))
                                               (if (member (vector-ref (vector-ref board i) j) seen)
                                                   #f
                                                   (loop2 (+ j 1) (cons (vector-ref (vector-ref board i) j) seen)))
                                               seen))))
                          (let ((loop2res (loop2 startj seen)))
                            (if loop2res
                                (loop1 (+ i 1) loop2res)
                                #f)))
                        #t))))
    (loop1 starti '())))

(define all-rows (fork (walk-rows)))
(define all-cols (fork (walk-cols)))
(define square1 (fork (check-square 0 0)))
(define square2 (fork (check-square 0 3)))
(define square3 (fork (check-square 0 6)))
(define square4 (fork (check-square 3 0)))
(define square5 (fork (check-square 3 3)))
(define square6 (fork (check-square 3 6)))
(define square7 (fork (check-square 6 0)))
(define square8 (fork (check-square 6 3)))
(define square9 (fork (check-square 6 6)))

(and
 (join all-rows) (join all-cols)
 (join square1) (join square2) (join square3)
 (join square4) (join square5) (join square6)
 (join square7) (join square8) (join square9))
