(define counter 0)
(define lock (c/new-lock))
(define (inc)
  (c/acquire lock)
  (set! counter (+ counter 1))
  (c/release lock))
(define (dec)
  (c/acquire lock)
  (set! counter (- counter 1))
  (c/release lock))
(define t1 (c/spawn (inc)))
(define t2 (c/spawn (dec)))
(define t3 (c/spawn (inc)))
(define t4 (c/spawn (inc)))
(define t5 (c/spawn (inc)))
(define t6 (c/spawn (inc)))
(define t7 (c/spawn (inc)))
(c/join t1)
(c/join t2)
counter
