(letrec ((v 1)
         (thread1 (lambda ()
                    (if (> v 0)
                        (display v))))
         (thread2 (lambda ()
                    (set! v 0)))
         (t1 (spawn (thread1)))
         (t2 (spawn (thread2))))
  (join t1)
  (join t2))
