;; Inspired from Fig. 2 of "Learning from Mistakes -- A Comprehensive Study on Real World Concurrency Bug Characteristics"
(letrec ((struct '())
         (create-struct (lambda () '(foo bar)))
         (thread1 (lambda ()
                    (set! struct (create-struct))))
         (thread2 (lambda ()
                    (car struct)))
         (t1 (spawn (thread1)))
         (t2 (spawn (thread2))))
  (join t1)
  (join t2))
