(letrec ((flag-0 #f)
         (flag-1 #f)
         (turn 0)
         (counter 0)
         (p0 (lambda ()
               (set! flag-0 #t)
               (letrec ((wait (lambda ()
                                (if (and flag-1 (= turn 1))
                                    (wait)
                                    #t))))
                 (wait)
                 (set! counter (+ counter 1))
                 (set! flag-0 #f))))
         (p1 (lambda ()
               (set! flag-1 #t)
               (letrec ((wait (lambda ()
                                (if (and flag-0 (= turn 0))
                                    (wait)
                                    #t))))
                 (wait)
                 (set! counter (+ counter 1))
                 (set! flag-1 #f))))
         (t0 (spawn (p0)))
         (t1 (spawn (p1))))
  (join t0)
  (join t1)
  counter)
