(letrec ((counter 0)
         (inc (lambda ()
                (set! counter (+ counter 1))))
         (dec (lambda ()
                (set! counter (- counter 1))))
         (t1 (spawn (inc)))
         (t2 (spawn (dec)))
         (t3 (spawn (inc)))
         (t4 (spawn (dec)))
         (t5 (spawn (inc)))
         (t6 (spawn (dec))))
  (join t1)
  (join t2)
  (join t3)
  (join t4)
  (join t5)
  (join t6)
  counter)
